# Generated by Django 5.2.17 on 2026-10-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('successful', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook delivery log',
                'verbose_name_plural': 'Webhook delivery logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
