# Generated by Django 5.2.17 on 2026-10-07 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productattribute_is_variant_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Maximum units sold at the sale price. 0 = unlimited.')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Flash sale',
                'verbose_name_plural': 'Flash sales',
                'ordering': ['-start_at'],
            },
        ),
    ]
