# Generated by Django 5.2.17 on 2026-10-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='provider_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
