# Generated by Django 5.2.17 on 2026-10-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=32)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('installed', 'Installed'),
                            ('enabled', 'Enabled'),
                            ('disabled', 'Disabled'),
                        ],
                        default='installed',
                        max_length=16,
                    ),
                ),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plugin state',
                'verbose_name_plural': 'Plugin states',
            },
        ),
    ]
