# Generated by Django 5.2.17 on 2026-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, default='global', max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('value', models.JSONField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'constraints': [models.UniqueConstraint(fields=('namespace', 'key'), name='uniq_setting_ns_key')],
            },
        ),
    ]
