# Generated by Django 5.2.17 on 2026-10-05 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productattribute_is_variant_option_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('backorder_allowed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('receive', 'Receive'), ('ship', 'Ship'), ('reserve', 'Reserve'), ('release', 'Release'), ('adjust', 'Adjust'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in')], max_length=20)),
                ('stock_delta', models.IntegerField(default=0)),
                ('reserved_delta', models.IntegerField(default=0)),
                ('resulting_stock', models.PositiveIntegerField()),
                ('resulting_reserved', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory transaction',
                'verbose_name_plural': 'Inventory transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address_line', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='stores.store')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse location',
                'verbose_name_plural': 'Warehouse locations',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.warehouselocation'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='uniq_warehouse_location'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('warehouse', 'product'), name='uniq_inventory_warehouse_product'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('warehouse', 'variant'), name='uniq_inventory_warehouse_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('variant__isnull', True)), models.Q(('product__isnull', True), ('variant__isnull', False)), _connector='OR'), name='inventory_target_xor'),
        ),
    ]
