# Generated by Django 5.2.17 on 2026-10-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_variant_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select'), ('multi_select', 'Multi-select'), ('color', 'Color'), ('size', 'Size')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductAttributeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='catalog.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product attribute assignment',
                'verbose_name_plural': 'Product attribute assignments',
                'constraints': [models.UniqueConstraint(fields=('product', 'attribute'), name='uniq_product_attribute')],
            },
        ),
    ]
