# Generated by Django 5.2.17 on 2026-10-05 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('supported_currencies', models.JSONField(blank=True, default=list)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('products_per_page', models.PositiveIntegerField(default=20)),
                ('allow_guest_checkout', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('ssl_enabled', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store domain',
                'verbose_name_plural': 'Store domains',
            },
        ),
    ]
