# Generated by Django 5.2.17 on 2026-10-07 20:43

import uuid
from django.db import migrations, models


def seed_languages(apps, schema_editor):
    Language = apps.get_model("stores", "Language")
    Language.objects.get_or_create(
        code="en",
        defaults={"name": "English", "is_active": True, "is_default": True, "ordering": 0},
    )
    Language.objects.get_or_create(
        code="fa",
        defaults={
            "name": "فارسی",
            "is_active": True,
            "direction": "rtl",
            "flag": "🇮🇷",
            "ordering": 1,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('ltr', 'LTR'), ('rtl', 'RTL')], default='ltr', max_length=3)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['ordering', 'code'],
            },
        ),
        migrations.RunPython(
            seed_languages,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
